version: "3.3"

services:
  db:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "leoni"
  server:
    build: .
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/leoni?schema=public"